In [20]:
##Write a Python Program to Add Two Matrices?

In [34]:
import numpy as np

m1=np.matrix(np.random.randint(0,10,(5,6)))
m2=np.matrix(np.random.randint(0,20,(5,6)))
np.add(m1,m2)


matrix([[ 8, 17,  6,  6,  9, 18],
        [ 5,  0,  4,  6,  4,  4],
        [ 9, 23, 15,  7, 25,  7],
        [18, 19,  1, 22, 18, 10],
        [12, 12,  8,  2,  7, 13]])

In [ ]:
#Write a Python Program to Multiply Two Matrices?

In [30]:
import numpy as np

m1=np.matrix(np.random.randint(0,10,(5,6)))
m2=np.matrix(np.random.randint(0,20,(6,5)))
#np.multiply(m1,m2)
m1@m2


matrix([[248, 162, 238, 119, 169],
        [468, 439, 396, 291, 336],
        [419, 335, 358, 212, 315],
        [436, 377, 336, 157, 262],
        [329, 237, 308, 169, 196]])

In [ ]:
#Write a Python Program to Transpose a Matrix?

In [37]:
m3=np.transpose(m1)
print(m1,"\n")
print("\n",m3)

[[8 8 6 3 3 6]
 [4 0 4 2 1 1]
 [0 6 0 6 7 2]
 [3 0 1 3 8 9]
 [6 6 3 0 7 5]] 


 [[8 4 0 3 6]
 [8 0 6 0 6]
 [6 4 0 1 3]
 [3 2 6 3 0]
 [3 1 7 8 7]
 [6 1 2 9 5]]


In [ ]:
#Write a Python Program to Sort Words in Alphabetic Order?

In [2]:
class Sort:
    def receive(self):
        words=[]
        
        while(True):
            word=input("Enter the words to sort ['q'-->QUIT]")
            if word=='q' or word=='Q':
                break
            else:
                words.append(word)            
        self.put_words(words)
        
                
    def put_words(self,words):        
        
        words.sort()
        print(words)
        
        
        

s=Sort()
s.receive()
            

Enter the words to sort ['q'-->QUIT]suriya
Enter the words to sort ['q'-->QUIT]narayanan
Enter the words to sort ['q'-->QUIT]perumal
Enter the words to sort ['q'-->QUIT]guna
Enter the words to sort ['q'-->QUIT]vikram
Enter the words to sort ['q'-->QUIT]karthi
Enter the words to sort ['q'-->QUIT]kaviya
Enter the words to sort ['q'-->QUIT]q
['guna', 'karthi', 'kaviya', 'narayanan', 'perumal', 'suriya', 'vikram']


In [ ]:
#Write a Python Program to Remove Punctuation From a String?

In [25]:
class Remove_Punctuation:
    def __init__(self):
        self.name=input("Enter a string with punctuation [q to quit]")
        if name=='q' or name=="Q":
            pass
        else:
            self.replace_punctuation()
    
    def replace_punctuation(self):
        pun=[".",",","!","'","\"",":",";"]
        for i in range(0,len(pun)):
            if pun[i] in self.name:
                self.name=self.name.replace(pun[i],"")
        print(f"Name after removing the punctuation {self.name}")
        


name="su..,\"\"''!\"riya"
r=Remove_Punctuation()


Enter a string with punctuation [q to quit]sur:;"'.,!iya
Name after removing the punctuation suriya
